### ISSUE TITLE
about scale factor

### ISSUE THREAD

**Issue by shiyuleixia** [zsyOAOA/InvSR#9]
# Super-resolution settings
basesr:
  sf: 1
  chopping:     # for latent diffusion
    pch_size: 512
    weight_type: Gaussian

I change the scale factor to 1,but it dosen't work:
![image](https://github.com/user-attachments/assets/2398f794-58aa-495a-a416-ff0bcce404b3)

**Comment by zsyOAOA** [comment]
Currently, our model only supports x4 SR task.

**Comment by flynnamy** [comment]
How to modify this? @zsyOAOA

**Comment by sunzhe09** [comment]
+1

**Comment by zsyOAOA** [comment]
@sunzhe09 @flynnamy I have stated that our model only supports the x4 super-resolution task recently.

**Comment by flynnamy** [comment]
How to modify this? I do not understand why the scale factor has been fixed? @zsyOAOA

**Comment by zsyOAOA** [comment]
> How to modify this? I do not understand why the scale factor has been fixed? @zsyOAOA

Our noise predictor is trained to predict the noise map in the latent space of VQGAN, which is downsampled 8x times spatially. Thus we have to adjust the number of downsampling operators according to the scale factor. E.g., for x4 SR task, the noise predictor contains two downsampling layers as shown in [config[(https://github.com/zsyOAOA/InvSR/blob/master/configs/sample-sd-turbo.yaml#L43) to match the resolution of latent space. Therefore, we can't directly modify the scale factor! @flynnamy

**Comment by ManuBN786** [comment]
Thant means even if I put sf:1 during training, I still cant generate 1X SR at prediction?
